/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EntropyHandleLifecycleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "entropyOracle"
      | "entropyRequests"
      | "getEntropyOracle"
      | "getHandle"
      | "isInitialized"
      | "requestEntropy"
      | "storeHandle"
      | "useEntropyHandle"
      | "useHandle"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EntropyHandleUsed"
      | "EntropyRequested"
      | "HandleStored"
      | "HandleUsed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entropyRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getHandle", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestEntropy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storeHandle",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "useEntropyHandle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "useHandle", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getHandle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeHandle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "useEntropyHandle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "useHandle", data: BytesLike): Result;
}

export namespace EntropyHandleUsedEvent {
  export type InputTuple = [requestId: BigNumberish];
  export type OutputTuple = [requestId: bigint];
  export interface OutputObject {
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntropyRequestedEvent {
  export type InputTuple = [requestId: BigNumberish, caller: AddressLike];
  export type OutputTuple = [requestId: bigint, caller: string];
  export interface OutputObject {
    requestId: bigint;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HandleStoredEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HandleUsedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EntropyHandleLifecycle extends BaseContract {
  connect(runner?: ContractRunner | null): EntropyHandleLifecycle;
  waitForDeployment(): Promise<this>;

  interface: EntropyHandleLifecycleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  entropyOracle: TypedContractMethod<[], [string], "view">;

  entropyRequests: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getEntropyOracle: TypedContractMethod<[], [string], "view">;

  getHandle: TypedContractMethod<[], [string], "view">;

  isInitialized: TypedContractMethod<[], [boolean], "view">;

  requestEntropy: TypedContractMethod<[tag: BytesLike], [bigint], "payable">;

  storeHandle: TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  useEntropyHandle: TypedContractMethod<
    [requestId: BigNumberish],
    [string],
    "nonpayable"
  >;

  useHandle: TypedContractMethod<[], [string], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "entropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "entropyRequests"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getEntropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getHandle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "requestEntropy"
  ): TypedContractMethod<[tag: BytesLike], [bigint], "payable">;
  getFunction(
    nameOrSignature: "storeHandle"
  ): TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "useEntropyHandle"
  ): TypedContractMethod<[requestId: BigNumberish], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "useHandle"
  ): TypedContractMethod<[], [string], "nonpayable">;

  getEvent(
    key: "EntropyHandleUsed"
  ): TypedContractEvent<
    EntropyHandleUsedEvent.InputTuple,
    EntropyHandleUsedEvent.OutputTuple,
    EntropyHandleUsedEvent.OutputObject
  >;
  getEvent(
    key: "EntropyRequested"
  ): TypedContractEvent<
    EntropyRequestedEvent.InputTuple,
    EntropyRequestedEvent.OutputTuple,
    EntropyRequestedEvent.OutputObject
  >;
  getEvent(
    key: "HandleStored"
  ): TypedContractEvent<
    HandleStoredEvent.InputTuple,
    HandleStoredEvent.OutputTuple,
    HandleStoredEvent.OutputObject
  >;
  getEvent(
    key: "HandleUsed"
  ): TypedContractEvent<
    HandleUsedEvent.InputTuple,
    HandleUsedEvent.OutputTuple,
    HandleUsedEvent.OutputObject
  >;

  filters: {
    "EntropyHandleUsed(uint256)": TypedContractEvent<
      EntropyHandleUsedEvent.InputTuple,
      EntropyHandleUsedEvent.OutputTuple,
      EntropyHandleUsedEvent.OutputObject
    >;
    EntropyHandleUsed: TypedContractEvent<
      EntropyHandleUsedEvent.InputTuple,
      EntropyHandleUsedEvent.OutputTuple,
      EntropyHandleUsedEvent.OutputObject
    >;

    "EntropyRequested(uint256,address)": TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;
    EntropyRequested: TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;

    "HandleStored(address)": TypedContractEvent<
      HandleStoredEvent.InputTuple,
      HandleStoredEvent.OutputTuple,
      HandleStoredEvent.OutputObject
    >;
    HandleStored: TypedContractEvent<
      HandleStoredEvent.InputTuple,
      HandleStoredEvent.OutputTuple,
      HandleStoredEvent.OutputObject
    >;

    "HandleUsed()": TypedContractEvent<
      HandleUsedEvent.InputTuple,
      HandleUsedEvent.OutputTuple,
      HandleUsedEvent.OutputObject
    >;
    HandleUsed: TypedContractEvent<
      HandleUsedEvent.InputTuple,
      HandleUsedEvent.OutputTuple,
      HandleUsedEvent.OutputObject
    >;
  };
}
