/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HandleLifecycleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "getHandle"
      | "isInitialized"
      | "storeHandle"
      | "useHandle"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "HandleStored" | "HandleUsed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getHandle", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "storeHandle",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "useHandle", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getHandle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeHandle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "useHandle", data: BytesLike): Result;
}

export namespace HandleStoredEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HandleUsedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HandleLifecycle extends BaseContract {
  connect(runner?: ContractRunner | null): HandleLifecycle;
  waitForDeployment(): Promise<this>;

  interface: HandleLifecycleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getHandle: TypedContractMethod<[], [string], "view">;

  isInitialized: TypedContractMethod<[], [boolean], "view">;

  storeHandle: TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  useHandle: TypedContractMethod<[], [string], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHandle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "storeHandle"
  ): TypedContractMethod<
    [encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "useHandle"
  ): TypedContractMethod<[], [string], "nonpayable">;

  getEvent(
    key: "HandleStored"
  ): TypedContractEvent<
    HandleStoredEvent.InputTuple,
    HandleStoredEvent.OutputTuple,
    HandleStoredEvent.OutputObject
  >;
  getEvent(
    key: "HandleUsed"
  ): TypedContractEvent<
    HandleUsedEvent.InputTuple,
    HandleUsedEvent.OutputTuple,
    HandleUsedEvent.OutputObject
  >;

  filters: {
    "HandleStored(address)": TypedContractEvent<
      HandleStoredEvent.InputTuple,
      HandleStoredEvent.OutputTuple,
      HandleStoredEvent.OutputObject
    >;
    HandleStored: TypedContractEvent<
      HandleStoredEvent.InputTuple,
      HandleStoredEvent.OutputTuple,
      HandleStoredEvent.OutputObject
    >;

    "HandleUsed()": TypedContractEvent<
      HandleUsedEvent.InputTuple,
      HandleUsedEvent.OutputTuple,
      HandleUsedEvent.OutputObject
    >;
    HandleUsed: TypedContractEvent<
      HandleUsedEvent.InputTuple,
      HandleUsedEvent.OutputTuple,
      HandleUsedEvent.OutputObject
    >;
  };
}
